package net.narutomod.client;

import net.minecraftforge.api.distmarker.Dist;
import net.minecraft.client.renderer.ItemBlockRenderTypes;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.entity.ThrownItemRenderer;
import net.minecraft.client.renderer.entity.player.PlayerRenderer;
import net.minecraftforge.client.event.RegisterParticleProvidersEvent;
import net.minecraftforge.client.event.RegisterDimensionSpecialEffectsEvent;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraft.client.gui.screens.MenuScreens;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.narutomod.NarutomodMod;
import net.narutomod.client.gui.JutsuScrollScreen;
import net.narutomod.client.gui.MedicalScrollScreen;
import net.narutomod.client.gui.RasenganScrollScreen;
import net.narutomod.client.model.AkatsukiRobeModel;
import net.narutomod.client.model.AnbuModel;
import net.narutomod.client.model.AsuraPathArmorModel;
import net.narutomod.client.model.BijuCloakModel;
import net.narutomod.client.model.BoneArmorModel;
import net.narutomod.client.model.Buddha1000Model;
import net.narutomod.client.model.ChibakuTenseiBallModel;
import net.narutomod.client.model.ClayC1Model;
import net.narutomod.client.model.ClayC2Model;
import net.narutomod.client.model.ClayC3Model;
import net.narutomod.client.model.DojutsuHelmetSnugModel;
import net.narutomod.client.model.EightTrigramsModel;
import net.narutomod.client.model.EightTailsModel;
import net.narutomod.client.model.EightyGodsModel;
import net.narutomod.client.model.FiveTailsModel;
import net.narutomod.client.model.FingerBoneModel;
import net.narutomod.client.model.FourTailsModel;
import net.narutomod.client.model.GaaraModel;
import net.narutomod.client.model.GedoStatueModel;
import net.narutomod.client.model.GiantDog2hModel;
import net.narutomod.client.model.HakuModel;
import net.narutomod.client.model.HakkeshoKeitenModel;
import net.narutomod.client.model.HirudoraTigerModel;
import net.narutomod.client.model.IceDomeModel;
import net.narutomod.client.model.IrukaSenseiModel;
import net.narutomod.client.model.JintonCubeModel;
import net.narutomod.client.model.KakashiModel;
import net.narutomod.client.model.KankuroAnimatedModel;
import net.narutomod.client.model.KikaichuBeetleModel;
import net.narutomod.client.model.KisameHoshigakiModel;
import net.narutomod.client.model.KirinModel;
import net.narutomod.client.model.KingOfHellModel;
import net.narutomod.client.model.KurotsuchiModel;
import net.narutomod.client.model.LightningBeastModel;
import net.narutomod.client.model.MeltingJutsuModel;
import net.narutomod.client.model.MightGuyModel;
import net.narutomod.client.model.NightGuyDragonModel;
import net.narutomod.client.model.NinjaArmorModel;
import net.narutomod.client.model.NineTailsModel;
import net.narutomod.client.model.OneTailModel;
import net.narutomod.client.model.PretaShieldModel;
import net.narutomod.client.model.PurpleDragonModel;
import net.narutomod.client.model.PuppetHirukoModel;
import net.narutomod.client.model.PuppetKarasuModel;
import net.narutomod.client.model.PuppetSanshouoModel;
import net.narutomod.client.model.PuppetScrollModel;
import net.narutomod.client.model.RasenganModel;
import net.narutomod.client.model.RasenshurikenModel;
import net.narutomod.client.model.RinneganRobeModel;
import net.narutomod.client.model.SakuraHarunoModel;
import net.narutomod.client.model.SandLevitationModel;
import net.narutomod.client.model.SealingModel;
import net.narutomod.client.model.SevenTailsModel;
import net.narutomod.client.model.SixTailsModel;
import net.narutomod.client.model.SlugModel;
import net.narutomod.client.model.Snake8HeadModel;
import net.narutomod.client.model.Snake8HeadsModel;
import net.narutomod.client.model.SnakeModel;
import net.narutomod.client.model.SpikeModel;
import net.narutomod.client.model.SteamArmorModel;
import net.narutomod.client.model.SusanooClothedModel;
import net.narutomod.client.model.SusanooSkeletonModel;
import net.narutomod.client.model.SusanooWingedModel;
import net.narutomod.client.model.TailBeastBallModel;
import net.narutomod.client.model.TemariModel;
import net.narutomod.client.model.TenTailsModel;
import net.narutomod.client.model.TentenModel;
import net.narutomod.client.model.ThreeTailsModel;
import net.narutomod.client.model.ToadModel;
import net.narutomod.client.model.TruthSeekerBallModel;
import net.narutomod.client.model.TwoTailsModel;
import net.narutomod.client.model.UchihaArmorModel;
import net.narutomod.client.model.VillageNinjaModel;
import net.narutomod.client.model.WaterDragonModel;
import net.narutomod.client.model.WaterSharkModel;
import net.narutomod.client.model.WoodGolemModel;
import net.narutomod.client.model.WoodSegmentModel;
import net.narutomod.client.model.ZabuzaMomochiModel;
import net.narutomod.client.particle.NarutoParticleProvider;
import net.narutomod.client.renderer.AnbuRenderer;
import net.narutomod.client.renderer.AshBonesProjectileRenderer;
import net.narutomod.client.renderer.AsakujakuFireballRenderer;
import net.narutomod.client.renderer.AltCamViewRenderer;
import net.narutomod.client.renderer.BijuCloakLayer;
import net.narutomod.client.renderer.BlackReceiverProjectileRenderer;
import net.narutomod.client.renderer.BrackenDanceRenderer;
import net.narutomod.client.renderer.BiggerMeRenderer;
import net.narutomod.client.renderer.BuddhaArmRenderer;
import net.narutomod.client.renderer.Buddha1000Renderer;
import net.narutomod.client.renderer.BugSwarmRenderer;
import net.narutomod.client.renderer.CellularActivationRenderer;
import net.narutomod.client.renderer.ChibakuSatelliteRenderer;
import net.narutomod.client.renderer.ChibakuTenseiBallRenderer;
import net.narutomod.client.renderer.ChidoriRenderer;
import net.narutomod.client.renderer.CrowRenderer;
import net.narutomod.client.renderer.EarthBlocksRenderer;
import net.narutomod.client.renderer.EarthSpearRenderer;
import net.narutomod.client.renderer.EightGatesPlayerOverlayLayer;
import net.narutomod.client.renderer.EightTrigramsRenderer;
import net.narutomod.client.renderer.EightTailsRenderer;
import net.narutomod.client.renderer.EightyGodsRenderer;
import net.narutomod.client.renderer.ExplosiveKunaiProjectileRenderer;
import net.narutomod.client.renderer.ExplosiveClayRenderer;
import net.narutomod.client.renderer.ExplosiveCloneRenderer;
import net.narutomod.client.renderer.FingerBoneRenderer;
import net.narutomod.client.renderer.FiveTailsRenderer;
import net.narutomod.client.renderer.FourTailsRenderer;
import net.narutomod.client.renderer.FutonChakraFlowRenderer;
import net.narutomod.client.renderer.GaaraRenderer;
import net.narutomod.client.renderer.GedoStatueRenderer;
import net.narutomod.client.renderer.GiantDog2hRenderer;
import net.narutomod.client.renderer.HakuRenderer;
import net.narutomod.client.renderer.HakkeshoKeitenRenderer;
import net.narutomod.client.renderer.HiramekareiEffectRenderer;
import net.narutomod.client.renderer.HirudoraRenderer;
import net.narutomod.client.renderer.IceDomeRenderer;
import net.narutomod.client.renderer.IceSpikeRenderer;
import net.narutomod.client.renderer.IceSpearRenderer;
import net.narutomod.client.renderer.InventoryItemLayer;
import net.narutomod.client.renderer.IrukaSenseiRenderer;
import net.narutomod.client.renderer.ItachiRenderer;
import net.narutomod.client.renderer.JinchurikiCloneRenderer;
import net.narutomod.client.renderer.JintonBeamRenderer;
import net.narutomod.client.renderer.JintonCubeRenderer;
import net.narutomod.client.renderer.KakashiRenderer;
import net.narutomod.client.renderer.KankuroRenderer;
import net.narutomod.client.renderer.KagutsuchiFireballRenderer;
import net.narutomod.client.renderer.KamuiShurikenRenderer;
import net.narutomod.client.renderer.KatonFireballRenderer;
import net.narutomod.client.renderer.KibaBladeAuraRenderer;
import net.narutomod.client.renderer.KisameHoshigakiRenderer;
import net.narutomod.client.renderer.KingOfHellRenderer;
import net.narutomod.client.renderer.KirinRenderer;
import net.narutomod.client.renderer.KunaiProjectileRenderer;
import net.narutomod.client.renderer.KusanagiSwordRenderer;
import net.narutomod.client.renderer.KurotsuchiRenderer;
import net.narutomod.client.renderer.KageBunshinRenderer;
import net.narutomod.client.renderer.LaserRingRenderer;
import net.narutomod.client.renderer.LavaChakraModeLayer;
import net.narutomod.client.renderer.LavaChakraModeRenderer;
import net.narutomod.client.renderer.LightningArcRenderer;
import net.narutomod.client.renderer.LightningBeastRenderer;
import net.narutomod.client.renderer.LimboCloneRenderer;
import net.narutomod.client.renderer.MagmaBallRenderer;
import net.narutomod.client.renderer.MeltingJutsuRenderer;
import net.narutomod.client.renderer.MightGuyRenderer;
import net.narutomod.client.renderer.MindTransferSelfRenderer;
import net.narutomod.client.renderer.NightGuyDragonRenderer;
import net.narutomod.client.renderer.NineTailsRenderer;
import net.narutomod.client.renderer.NoopEntityRenderer;
import net.narutomod.client.renderer.NuibariSwordRenderer;
import net.narutomod.client.renderer.OneTailRenderer;
import net.narutomod.client.renderer.PortingDummyRenderer;
import net.narutomod.client.renderer.PretaShieldRenderer;
import net.narutomod.client.renderer.PurpleDragonRenderer;
import net.narutomod.client.renderer.PuppetHirukoRenderer;
import net.narutomod.client.renderer.PuppetKarasuRenderer;
import net.narutomod.client.renderer.PuppetSanshouoRenderer;
import net.narutomod.client.renderer.PuppetScrollRenderer;
import net.narutomod.client.renderer.RasenganDebugRenderer;
import net.narutomod.client.renderer.RasenshurikenRenderer;
import net.narutomod.client.renderer.ReplacementCloneRenderer;
import net.narutomod.client.renderer.SakuraHarunoRenderer;
import net.narutomod.client.renderer.SageModeHelmetLayer;
import net.narutomod.client.renderer.SandLevitationRenderer;
import net.narutomod.client.renderer.ScorchOrbRenderer;
import net.narutomod.client.renderer.SekizoRenderer;
import net.narutomod.client.renderer.SealingChainsRenderer;
import net.narutomod.client.renderer.SealingRenderer;
import net.narutomod.client.renderer.SevenTailsRenderer;
import net.narutomod.client.renderer.ShadowImitationRenderer;
import net.narutomod.client.renderer.SixTailsRenderer;
import net.narutomod.client.renderer.SlugSummonRenderer;
import net.narutomod.client.renderer.Snake8HeadRenderer;
import net.narutomod.client.renderer.Snake8HeadsRenderer;
import net.narutomod.client.renderer.SnakeSummonRenderer;
import net.narutomod.client.renderer.SpecialEffectRenderer;
import net.narutomod.client.renderer.SpikeRenderer;
import net.narutomod.client.renderer.SuitonStreamRenderer;
import net.narutomod.client.renderer.SusanooClothedRenderer;
import net.narutomod.client.renderer.SusanooSkeletonRenderer;
import net.narutomod.client.renderer.SusanooWingedRenderer;
import net.narutomod.client.renderer.TailBeastBallRenderer;
import net.narutomod.client.renderer.TemariRenderer;
import net.narutomod.client.renderer.TenTailsRenderer;
import net.narutomod.client.renderer.TenseiBakuGoldRenderer;
import net.narutomod.client.renderer.TenseiBakuSilverRenderer;
import net.narutomod.client.renderer.TenseiganOrbRenderer;
import net.narutomod.client.renderer.TentenRenderer;
import net.narutomod.client.renderer.ThreeTailsRenderer;
import net.narutomod.client.renderer.ToadSummonRenderer;
import net.narutomod.client.renderer.TransformationJutsuRenderer;
import net.narutomod.client.renderer.TruthSeekerBallRenderer;
import net.narutomod.client.renderer.TwoTailsRenderer;
import net.narutomod.client.renderer.VillageNinjaRenderer;
import net.narutomod.client.renderer.WaterDragonRenderer;
import net.narutomod.client.renderer.WaterSharkRenderer;
import net.narutomod.client.renderer.WhiteZetsuRenderer;
import net.narutomod.client.renderer.WoodArmRenderer;
import net.narutomod.client.renderer.WoodBurialRenderer;
import net.narutomod.client.renderer.WoodGolemRenderer;
import net.narutomod.client.renderer.YasakaMagatamaRenderer;
import net.narutomod.client.renderer.ZabuzaMomochiRenderer;
import net.narutomod.registry.ModEntityTypes;
import net.narutomod.registry.ModBlocks;
import net.narutomod.registry.ModMenuTypes;
import net.narutomod.registry.ModParticleTypes;
import net.narutomod.registry.ModRegistries;

@Mod.EventBusSubscriber(modid = NarutomodMod.MODID, bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public final class ClientModEvents {
    private ClientModEvents() {
    }

    @SubscribeEvent
    public static void onClientSetup(FMLClientSetupEvent event) {
        event.enqueueWork(() -> {
            MenuScreens.register(ModMenuTypes.JUTSU_SCROLL.get(), JutsuScrollScreen::new);
            MenuScreens.register(ModMenuTypes.RASENGAN_SCROLL.get(), RasenganScrollScreen::new);
            MenuScreens.register(ModMenuTypes.MEDICAL_SCROLL.get(), MedicalScrollScreen::new);
            ItemBlockRenderTypes.setRenderLayer(ModBlocks.WATER_STILL.get(), RenderType.translucent());
        });
        NarutomodMod.LOGGER.debug("Narutomod client setup hook ready");
    }

    @SubscribeEvent
    public static void registerEntityRenderers(EntityRenderersEvent.RegisterRenderers event) {
        event.registerEntityRenderer(ModRegistries.PORTING_DUMMY.get(), PortingDummyRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ALTCAMVIEWENTITY.get(), AltCamViewRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ANBU.get(), AnbuRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ASAKUJAKU_FIREBALL.get(), AsakujakuFireballRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.BIGGERME.get(), BiggerMeRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBRACKENDANCE.get(), BrackenDanceRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.BUGBALL.get(), BugSwarmRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.BUDDHA_ARM.get(), BuddhaArmRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.BUDDHA_1000.get(), Buddha1000Renderer::new);
        event.registerEntityRenderer(ModEntityTypes.C_1.get(), ExplosiveClayRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.C_2.get(), ExplosiveClayRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.C_3.get(), ExplosiveClayRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.CELLULAR_ACTIVATION.get(), CellularActivationRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.CHIBAKU_SATELLITE.get(), ChibakuSatelliteRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.CHIBAKU_TENSEI_BALL.get(), ChibakuTenseiBallRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.CHIDORI.get(), ChidoriRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.CHIDORI_SPEAR.get(), ChidoriRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.CROW.get(), CrowRenderer.provider());
        event.registerEntityRenderer(ModEntityTypes.EARTH_BLOCKS.get(), EarthBlocksRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.EARTH_SANDWICH.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.EARTH_SPEARS.get(), EarthSpearRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.EIGHT_TAILS.get(), EightTailsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.GROUND_SHOCK.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.EIGHTTRIGRAMSENTITY.get(), EightTrigramsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITY80GODS.get(), EightyGodsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYEARTHWALL.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETASURACANON.get(), ThrownItemRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETASHBONES.get(), AshBonesProjectileRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETBLACK_RECEIVER.get(), BlackReceiverProjectileRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETFOLDING_FAN.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETHIRAMEKAREI_SWORD.get(), HiramekareiEffectRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETSCROLL_KARASU.get(), PuppetScrollRenderer::karasu);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETSCROLL_SANSHOUO.get(), PuppetScrollRenderer::sanshouo);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETSENJUTSU.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETKAMUISHURIKEN.get(), KamuiShurikenRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETKUNAI.get(), KunaiProjectileRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETKUNAI_EXPLOSIVE.get(), ExplosiveKunaiProjectileRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETSHURIKEN.get(), ThrownItemRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETSMOKE_BOMB.get(), ThrownItemRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.FALSE_DARKNESS.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.FIVE_TAILS.get(), FiveTailsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.FINGER_BONE.get(), FingerBoneRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.FOUR_TAILS.get(), FourTailsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.FUTONCHAKRAFLOW.get(), FutonChakraFlowRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.FUTON_GREAT_BREAKTHROUGH.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.FUTON_VACUUM.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.FUTTON_MIST.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.GAARA.get(), GaaraRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.GAMABUNTA.get(),
                context -> new ToadSummonRenderer<>(context, entity -> NarutomodMod.location("textures/gamabunta.png"), true));
        event.registerEntityRenderer(ModEntityTypes.GEDO_STATUE.get(), GedoStatueRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.GIANT_DOG_2H.get(), GiantDog2hRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.HAKKESHOKEITENENTITY.get(), HakkeshoKeitenRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.HAKU.get(), HakuRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.HIDING_IN_ASH.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYHIDINGINROCK.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYHIRUDORA.get(), HirudoraRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ICE_DOME.get(), IceDomeRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ICE_PRISON.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ICE_SPIKE.get(), IceSpikeRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ICE_SPEAR.get(), IceSpearRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.INTON_RAIHA.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.IRUKA_SENSEI.get(), IrukaSenseiRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.JINCHURIKI_CLONE.get(), JinchurikiCloneRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.JINTONBEAM.get(), JintonBeamRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.JINTONCUBE.get(), JintonCubeRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYKAGUTSUCHISWORDBIGFIREBALL.get(), KagutsuchiFireballRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYKAGUTSUCHISWORDFIREBALL.get(), KagutsuchiFireballRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ITACHI.get(), ItachiRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.KAKASHI.get(), KakashiRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.KANKURO.get(), KankuroRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.KAGE_BUNSHIN.get(), KageBunshinRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.KATONFIREBALL.get(), KatonFireballRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.KATONFIRESTREAM.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETKIBA_BLADES.get(), KibaBladeAuraRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.KINGOFHELLENTITY.get(), KingOfHellRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETKUSANAGI_SWORD.get(), KusanagiSwordRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYBULLETNUIBARI_SWORD.get(), NuibariSwordRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.EXPLOSIVE_CLONE.get(), ExplosiveCloneRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.KISAME_HOSHIGAKI.get(), KisameHoshigakiRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.KIRIN.get(), KirinRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.KUROTSUCHI.get(), KurotsuchiRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.LASER_CIRCUS.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.LASER_RING.get(), LaserRingRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.LAVA_CHAKRA_MODE.get(), LavaChakraModeRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.LIGHTNING_BEAST.get(), LightningBeastRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.LIGHTNING_ARC.get(), LightningArcRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.LIMBO_CLONE.get(), LimboCloneRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.MAGMABALL.get(), MagmaBallRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.MANDA.get(),
                context -> new SnakeSummonRenderer<>(context, entity -> NarutomodMod.location("textures/snake_purple.png")));
        event.registerEntityRenderer(ModEntityTypes.MELTING_JUTSU.get(), MeltingJutsuRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.MIGHTGUY.get(), MightGuyRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.MIND_TRANSFER.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.MIND_TRANSFER_SELF.get(), MindTransferSelfRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.NINE_TAILS.get(), NineTailsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYNGDRAGON.get(), NightGuyDragonRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.NINJA_IWA.get(), VillageNinjaRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.NINJA_KIRI.get(), VillageNinjaRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.NINJA_KONOHA.get(), VillageNinjaRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.NINJA_KUMO.get(), VillageNinjaRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.NINJA_SUNA.get(), VillageNinjaRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ONE_TAIL.get(), OneTailRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.PUPPET_HIRUKO.get(), PuppetHirukoRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.PUPPET_KARASU.get(), PuppetKarasuRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.PUPPET_SANSHOUO.get(), PuppetSanshouoRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.POISON_MIST.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.PRETASHIELDENTITY.get(), PretaShieldRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.PURPLE_DRAGON.get(), PurpleDragonRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.RAITONCHAKRAMODE.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.RANTON_KOGA.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.RASENGAN.get(), RasenganDebugRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.RASENSHURIKEN.get(), RasenshurikenRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.RANTONCLOUD.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.REPLACEMENTCLONE.get(), ReplacementCloneRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SAKURA_HARUNO.get(), SakuraHarunoRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SAND_BIND.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SAND_BULLET.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SAND_LEVITATION.get(), SandLevitationRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYJITONSHIELD.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SCORCHORB.get(), ScorchOrbRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ENTITYSEKIZO.get(), SekizoRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SEALING.get(), SealingRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SEALING_CHAINS.get(), SealingChainsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SEVEN_TAILS.get(), SevenTailsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SHADOW_IMITATION.get(), ShadowImitationRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SIX_TAILS.get(), SixTailsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SLUG.get(), SlugSummonRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SNAKE_8_HEAD1.get(), Snake8HeadRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SNAKE_8_HEADS.get(), Snake8HeadsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SNAKE_SUMMON.get(),
                context -> new SnakeSummonRenderer<>(context, entity -> entity.getSummonScale() > 4.0F
                        ? NarutomodMod.location("textures/snake_blue.png")
                        : NarutomodMod.location("textures/snake_white.png")));
        event.registerEntityRenderer(ModEntityTypes.SPECIALEFFECTENTITY.get(), SpecialEffectRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SPIKE.get(), SpikeRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SUSANOOCLOTHED.get(), SusanooClothedRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SUSANOOSKELETON.get(), SusanooSkeletonRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SUSANOOWINGED.get(), SusanooWingedRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SWAMP_PIT.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.TAILBEASTBALL.get(), TailBeastBallRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.TEMARI.get(), TemariRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.TEN_TAILS.get(), TenTailsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.THREE_TAILS.get(), ThreeTailsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SUITONMIST.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SUITON_SHARK.get(), WaterSharkRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.SUITONSTREAM.get(), SuitonStreamRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.TENSEI_BAKU_GOLD.get(), TenseiBakuGoldRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.TENSEI_BAKU_SILVER.get(), TenseiBakuSilverRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.TENSEIGANGUN.get(), TenseiganOrbRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.TENTEN.get(), TentenRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.TOAD_SUMMON.get(),
                context -> new ToadSummonRenderer<>(context, entity -> NarutomodMod.location("textures/toad1.png"), false));
        event.registerEntityRenderer(ModEntityTypes.TRANSFORMATION_JUTSU.get(), TransformationJutsuRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.TRUTHSEEKERBALL.get(), TruthSeekerBallRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.TWO_TAILS.get(), TwoTailsRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.UNRIVALED_STRENGTH.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.WATER_DRAGON.get(), WaterDragonRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.WATER_PRISON.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.WATER_SHOCKWAVE.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.WHITEZETSU.get(), WhiteZetsuRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.WOOD_ARM.get(), WoodArmRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.WOOD_BURIAL.get(), WoodBurialRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.WOOD_GOLEM.get(), WoodGolemRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.WOOD_PRISON.get(), NoopEntityRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.YASAKA_MAGATAMA.get(), YasakaMagatamaRenderer::new);
        event.registerEntityRenderer(ModEntityTypes.ZABUZA_MOMOCHI.get(), ZabuzaMomochiRenderer::new);
        ModEntityTypes.dummyTypes().forEach(entityType -> event.registerEntityRenderer(entityType.get(), PortingDummyRenderer::new));
    }

    @SubscribeEvent
    public static void registerDimensionSpecialEffects(RegisterDimensionSpecialEffectsEvent event) {
        event.register(NarutomodMod.location("kamui_dimension"), new KamuiDimensionEffects());
    }

    @SubscribeEvent
    public static void registerLayerDefinitions(EntityRenderersEvent.RegisterLayerDefinitions event) {
        event.registerLayerDefinition(AkatsukiRobeModel.LAYER_LOCATION, AkatsukiRobeModel::createBodyLayer);
        event.registerLayerDefinition(AnbuModel.LAYER_LOCATION, AnbuModel::createBodyLayer);
        event.registerLayerDefinition(AsuraPathArmorModel.LAYER_LOCATION, AsuraPathArmorModel::createBodyLayer);
        event.registerLayerDefinition(BijuCloakModel.LAYER_LOCATION, BijuCloakModel::createBodyLayer);
        event.registerLayerDefinition(BoneArmorModel.LAYER_LOCATION, BoneArmorModel::createBodyLayer);
        event.registerLayerDefinition(Buddha1000Model.LAYER_LOCATION, Buddha1000Model::createBodyLayer);
        event.registerLayerDefinition(ChibakuTenseiBallModel.LAYER_LOCATION, ChibakuTenseiBallModel::createBodyLayer);
        event.registerLayerDefinition(ClayC1Model.LAYER_LOCATION, ClayC1Model::createBodyLayer);
        event.registerLayerDefinition(ClayC2Model.LAYER_LOCATION, ClayC2Model::createBodyLayer);
        event.registerLayerDefinition(ClayC3Model.LAYER_LOCATION, ClayC3Model::createBodyLayer);
        event.registerLayerDefinition(DojutsuHelmetSnugModel.LAYER_LOCATION, DojutsuHelmetSnugModel::createBodyLayer);
        event.registerLayerDefinition(EightTrigramsModel.LAYER_LOCATION, EightTrigramsModel::createBodyLayer);
        event.registerLayerDefinition(EightTailsModel.LAYER_LOCATION, EightTailsModel::createBodyLayer);
        event.registerLayerDefinition(EightyGodsModel.LAYER_LOCATION, EightyGodsModel::createBodyLayer);
        event.registerLayerDefinition(FiveTailsModel.LAYER_LOCATION, FiveTailsModel::createBodyLayer);
        event.registerLayerDefinition(FingerBoneModel.LAYER_LOCATION, FingerBoneModel::createBodyLayer);
        event.registerLayerDefinition(FourTailsModel.LAYER_LOCATION, FourTailsModel::createBodyLayer);
        event.registerLayerDefinition(GaaraModel.LAYER_LOCATION, GaaraModel::createBodyLayer);
        event.registerLayerDefinition(GedoStatueModel.LAYER_LOCATION, GedoStatueModel::createBodyLayer);
        event.registerLayerDefinition(GiantDog2hModel.LAYER_LOCATION, GiantDog2hModel::createBodyLayer);
        event.registerLayerDefinition(HakuModel.LAYER_LOCATION, HakuModel::createBodyLayer);
        event.registerLayerDefinition(HakkeshoKeitenModel.LAYER_LOCATION, HakkeshoKeitenModel::createBodyLayer);
        event.registerLayerDefinition(HirudoraTigerModel.LAYER_LOCATION, HirudoraTigerModel::createBodyLayer);
        event.registerLayerDefinition(IceDomeModel.LAYER_LOCATION, IceDomeModel::createBodyLayer);
        event.registerLayerDefinition(IrukaSenseiModel.LAYER_LOCATION, IrukaSenseiModel::createBodyLayer);
        event.registerLayerDefinition(JintonCubeModel.LAYER_LOCATION, JintonCubeModel::createBodyLayer);
        event.registerLayerDefinition(KakashiModel.LAYER_LOCATION, KakashiModel::createBodyLayer);
        event.registerLayerDefinition(KankuroAnimatedModel.LAYER_LOCATION, KankuroAnimatedModel::createBodyLayer);
        event.registerLayerDefinition(KikaichuBeetleModel.LAYER_LOCATION, KikaichuBeetleModel::createBodyLayer);
        event.registerLayerDefinition(KisameHoshigakiModel.LAYER_LOCATION, KisameHoshigakiModel::createBodyLayer);
        event.registerLayerDefinition(KirinModel.LAYER_LOCATION, KirinModel::createBodyLayer);
        event.registerLayerDefinition(KingOfHellModel.LAYER_LOCATION, KingOfHellModel::createBodyLayer);
        event.registerLayerDefinition(KurotsuchiModel.LAYER_LOCATION, KurotsuchiModel::createBodyLayer);
        event.registerLayerDefinition(LightningBeastModel.LAYER_LOCATION, LightningBeastModel::createBodyLayer);
        event.registerLayerDefinition(MeltingJutsuModel.LAYER_LOCATION, MeltingJutsuModel::createBodyLayer);
        event.registerLayerDefinition(MightGuyModel.LAYER_LOCATION, MightGuyModel::createBodyLayer);
        event.registerLayerDefinition(NightGuyDragonModel.LAYER_LOCATION, NightGuyDragonModel::createBodyLayer);
        event.registerLayerDefinition(NinjaArmorModel.LAYER_LOCATION, NinjaArmorModel::createBodyLayer);
        event.registerLayerDefinition(NineTailsModel.LAYER_LOCATION, NineTailsModel::createBodyLayer);
        event.registerLayerDefinition(OneTailModel.LAYER_LOCATION, OneTailModel::createBodyLayer);
        event.registerLayerDefinition(PretaShieldModel.LAYER_LOCATION, PretaShieldModel::createBodyLayer);
        event.registerLayerDefinition(PurpleDragonModel.LAYER_LOCATION, PurpleDragonModel::createBodyLayer);
        event.registerLayerDefinition(PuppetHirukoModel.LAYER_LOCATION, PuppetHirukoModel::createBodyLayer);
        event.registerLayerDefinition(PuppetKarasuModel.LAYER_LOCATION, PuppetKarasuModel::createBodyLayer);
        event.registerLayerDefinition(PuppetSanshouoModel.LAYER_LOCATION, PuppetSanshouoModel::createBodyLayer);
        event.registerLayerDefinition(PuppetScrollModel.KARASU_LAYER_LOCATION, PuppetScrollModel::createKarasuBodyLayer);
        event.registerLayerDefinition(PuppetScrollModel.SANSHOUO_LAYER_LOCATION, PuppetScrollModel::createSanshouoBodyLayer);
        event.registerLayerDefinition(RasenganModel.LAYER_LOCATION, RasenganModel::createBodyLayer);
        event.registerLayerDefinition(RasenshurikenModel.LAYER_LOCATION, RasenshurikenModel::createBodyLayer);
        event.registerLayerDefinition(RinneganRobeModel.LAYER_LOCATION, RinneganRobeModel::createBodyLayer);
        event.registerLayerDefinition(SakuraHarunoModel.LAYER_LOCATION, SakuraHarunoModel::createBodyLayer);
        event.registerLayerDefinition(SandLevitationModel.LAYER_LOCATION, SandLevitationModel::createBodyLayer);
        event.registerLayerDefinition(SealingModel.LAYER_LOCATION, SealingModel::createBodyLayer);
        event.registerLayerDefinition(SevenTailsModel.LAYER_LOCATION, SevenTailsModel::createBodyLayer);
        event.registerLayerDefinition(SixTailsModel.LAYER_LOCATION, SixTailsModel::createBodyLayer);
        event.registerLayerDefinition(SlugModel.LAYER_LOCATION, SlugModel::createBodyLayer);
        event.registerLayerDefinition(Snake8HeadModel.LAYER_LOCATION, Snake8HeadModel::createBodyLayer);
        event.registerLayerDefinition(Snake8HeadsModel.LAYER_LOCATION, Snake8HeadsModel::createBodyLayer);
        event.registerLayerDefinition(SnakeModel.LAYER_LOCATION, SnakeModel::createBodyLayer);
        event.registerLayerDefinition(SpikeModel.LAYER_LOCATION, SpikeModel::createBodyLayer);
        event.registerLayerDefinition(SteamArmorModel.LAYER_LOCATION, SteamArmorModel::createBodyLayer);
        event.registerLayerDefinition(SusanooClothedModel.LAYER_LOCATION, SusanooClothedModel::createBodyLayer);
        event.registerLayerDefinition(SusanooSkeletonModel.LAYER_LOCATION, SusanooSkeletonModel::createBodyLayer);
        event.registerLayerDefinition(SusanooWingedModel.LAYER_LOCATION, SusanooWingedModel::createBodyLayer);
        event.registerLayerDefinition(TailBeastBallModel.LAYER_LOCATION, TailBeastBallModel::createBodyLayer);
        event.registerLayerDefinition(TemariModel.LAYER_LOCATION, TemariModel::createBodyLayer);
        event.registerLayerDefinition(TenTailsModel.LAYER_LOCATION, TenTailsModel::createBodyLayer);
        event.registerLayerDefinition(TentenModel.LAYER_LOCATION, TentenModel::createBodyLayer);
        event.registerLayerDefinition(ThreeTailsModel.LAYER_LOCATION, ThreeTailsModel::createBodyLayer);
        event.registerLayerDefinition(ToadModel.LAYER_LOCATION, ToadModel::createBodyLayer);
        event.registerLayerDefinition(TruthSeekerBallModel.LAYER_LOCATION, TruthSeekerBallModel::createBodyLayer);
        event.registerLayerDefinition(TwoTailsModel.LAYER_LOCATION, TwoTailsModel::createBodyLayer);
        event.registerLayerDefinition(UchihaArmorModel.LAYER_LOCATION, UchihaArmorModel::createBodyLayer);
        event.registerLayerDefinition(VillageNinjaModel.LAYER_LOCATION, VillageNinjaModel::createBodyLayer);
        event.registerLayerDefinition(WaterDragonModel.LAYER_LOCATION, WaterDragonModel::createBodyLayer);
        event.registerLayerDefinition(WaterSharkModel.LAYER_LOCATION, WaterSharkModel::createBodyLayer);
        event.registerLayerDefinition(WoodGolemModel.LAYER_LOCATION, WoodGolemModel::createBodyLayer);
        event.registerLayerDefinition(WoodSegmentModel.LAYER_LOCATION, WoodSegmentModel::createBodyLayer);
        event.registerLayerDefinition(ZabuzaMomochiModel.LAYER_LOCATION, ZabuzaMomochiModel::createBodyLayer);
    }

    @SubscribeEvent
    public static void addPlayerLayers(EntityRenderersEvent.AddLayers event) {
        for (String skinName : event.getSkins()) {
            PlayerRenderer renderer = event.getSkin(skinName);
            if (renderer != null) {
                renderer.addLayer(new LavaChakraModeLayer(renderer));
                renderer.addLayer(new EightGatesPlayerOverlayLayer(renderer));
                renderer.addLayer(new BijuCloakLayer<>(renderer, event.getEntityModels()));
                renderer.addLayer(new SageModeHelmetLayer(renderer, event.getEntityModels()));
                renderer.addLayer(new InventoryItemLayer(renderer));
            }
        }
    }

    @SubscribeEvent
    public static void registerParticleProviders(RegisterParticleProvidersEvent event) {
        ModParticleTypes.all().forEach(type -> event.registerSpriteSet(type.get(), NarutoParticleProvider::new));
    }
}
